### ISSUE TITLE
Visitors can sign up as a member, and a Stripe subscription is associated to a database user

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#10]
First pass is a hardcoding.

- [x] Wireframe and technical map
- [x] Implement MVP
  - [x] Create subscription
  - [x] Create user with related subscription
  - [x] Special member signup version of the allauth login view
    - [x] default to registration, not to login
    - [x] link to login as backup
      - [x] maintain the redirect back to the membership signup page, for logins
  - [x] Admins can configure shipping zones at a global level
    - name e.g. "ROW"
    - [countries selected from list via two letter country code (ISO alpha-2)](https://stripe.com/docs/payments/checkout/shipping#shipping-address-collection)
    - shipping rate
  - [x] Get rid of solidarity/regular options
  - [x] Instead, add a country selector before checkout which will determine what price (product base price + shipping zone rate) to intialise Stripe Checkout with
    - [x] Add Option 1 prices to the test env
      - [x] Base prices (monthly, annual cross sell, used for upfront price display)
      - [x] UK prices (monthly, annual cross sell)
      - [x] EU prices (monthly, annual cross sell)
      - [x] ROW prices (monthly, annual cross sell)
    - [x] Shipping zone is used to convert country picker to stripe price, via metadata
- [x] Fix CSP issues with checkout: https://stripe.com/docs/security/guide#content-security-policy

**Comment by janbaykara** [comment]
### Meeting notes about this

- Putting annual in the picker
- Shipping rates need to be set per country. UK is £2, and other websites have other rates.
- Archive the old subscription products when we come to launch
- Want to encourage annual or 12 books
- Where to put the login flow (A/B split test? User test?) — added to the user research backlog

**Comment by melaniepatrick** [comment]
So just thinking how to present the subs.
I think you are right that having a very limited number of choices on the initial page is good.
And you may also be right about not initially displaying the annual prices, but offering them as a follow-up option.
We do need to make a bigger deal of the solidarity sub though. So I'd like this to appear as one of 3 initial choices.

As a general rule it would be great to start getting people to pay by direct debit whenever we can. I notice the LRB makes everyone pay by direct debit, unless they are buying a gift subscription.

I'm attaching a pdf of my thinking so far, 2 slightly different ways of presenting essentially the same thing.
[New subscription and membership options.pdf](https://github.com/commonknowledge/leftbookclub/files/8383216/New.subscription.and.membership.options.pdf)

**Comment by janbaykara** [comment]
Going to reply to this with separate comments.

### Direct debits are possible

[We can collect Direct Debits via Checkout](https://stripe.com/docs/payments/payment-methods/bacs-debit#checkout)! I've enabled it! Here it is running on my local development enviornment right now:

<img width="410" alt="Screenshot 2022-03-30 at 22 18 50" src="https://user-images.githubusercontent.com/237556/160932677-10df5220-85d8-42a1-b835-d49ecf974c1b.png">

Just FYI, we can allow and disallow most payment methods. For example, we could straight-up disallow card payments, but not sure how wise that is.

**Comment by janbaykara** [comment]
### Re: Billing period for every-other-month plans

> Is it confusing that we bill Selected Books every other month? Do we just stick with our current set up and bill monthly and half the postage cost when this sub is chosen?*

Paying per month reminds you that it's about more than just books (e.g. community features) and demonstrates that this is a cheaper option, whereas billing on the shipping schedule means we can more ismply bill for shipping. I think we should go with which ever one is easier to implement, to be honest.

[I've added this to the user research backlog for us to explore in future](https://github.com/commonknowledge/leftbookclub/projects/4)

### Re: Community option, for people when they want to cancel

This is a great idea! Have made a note of this over at #15 (cancellation)

### Re: Gift options

I think these options might make sense, but might get us stuck during the initial release phase. I've made a note of this in the Github Issue on gift purchases (#6) and I propose that we return to this after May.

### Solidarity pricing

So the current prototype asks the user on one question at a time ([a helpful design principle](https://designnotes.blog.gov.uk/2015/07/03/one-thing-per-page/). First: what plan? Second: solidarity? Third: password. Fourth: payment.

<img width="1377" alt="Screenshot 2022-03-30 at 22 12 58" src="https://user-images.githubusercontent.com/237556/160931783-5fb4d505-56cf-4bfc-80e7-fc4a851ec1f0.png">

This is similar to how [GoodGym](https://goodgym.org) does it: you pick the 'donation level'. The difference is that GoodGym doesn't have different products to sell, just the one membership, so they don't need to worry about too much.

<img width="1165" alt="Screenshot 2022-03-29 at 15 41 44" src="https://user-images.githubusercontent.com/237556/160982329-4457059f-062c-4688-acb7-2c72098771a2.png">

Anyway, what you're suggesting in the doc is to have "solidarity" as one of the three options which as you say makes it more prominent. I think is an elegant solution.

### Shipping rates included in price

I've done some further research, and it looks like we are going to have to include postage in the pricing. So that is **Option 1**.

##### More detail on this
- Only Checkout with `payment` mode supports shipping options, but we need to use `subscription` mode to set up a recurring payment.
- We can't calculate shipping rates for the delivery address via Stripe Checkout, so we'll need to do that ourselves and then apply it to the purchase.
- (There is a [Orders API beta](https://stripe.com/docs/orders#open-orders) that I've enquired about getting access to, which would allow us to calculate shipping rates, but we can't rely on this for the initial release)

##### How we can do this

So, to determine the shipping rate, we can:

1. Configure per-country shipping rates in the CMS. This could be done like Shopify: create a "shipping zone" that applies to a range of countries, with a shipping rate attached.
2. Ask users for their country / "shipping zone" before checkout
3. Create a price for the product they've picked, that includes the relevant "shipping zone" rate.

We could potentially add the shipping rate [as a second product subscription](https://stripe.com/docs/billing/subscriptions/multiple-products) instead of factoring it into the primary subscription price, but I feel that might confuse things down the line with things like cancellation and pausing subscriptions.

**Comment by janbaykara** [comment]
### Re: Community option, for people when they want to cancel

This is a great idea! Have made a note of this over at #15 (cancellation)

**Comment by janbaykara** [comment]
### Re: Gift options

I think these options might make sense, but might get us stuck during the initial release phase. I've made a note of this in the Github Issue on gift purchases (#6) and I propose that we return to this after May.

**Comment by janbaykara** [comment]
### Solidarity pricing

So the current prototype asks the user on one question at a time ([a helpful design principle](https://designnotes.blog.gov.uk/2015/07/03/one-thing-per-page/). First: what plan? Second: solidarity? Third: password. Fourth: payment.

[(Screenshot)](https://user-images.githubusercontent.com/237556/160931783-5fb4d505-56cf-4bfc-80e7-fc4a851ec1f0.png) 

This is similar to how [GoodGym](https://goodgym.org) does it: you pick the 'donation level'. The difference is that GoodGym doesn't have different products to sell, just the one membership, so they don't need to worry about too much.

[(Screenshot)](https://user-images.githubusercontent.com/237556/160982329-4457059f-062c-4688-acb7-2c72098771a2.png)

Anyway, what you're suggesting in the doc is to have "solidarity" as one of the three options which as you say makes it more prominent. I think is an elegant solution and we should do it that way instead ✅

**Comment by janbaykara** [comment]
### Shipping rates included in price

I've done some further research, and it looks like we are going to have to include postage in the pricing. So that is **Option 1**.

#### More detail on this
- Only Checkout with `payment` mode supports shipping options, but we need to use `subscription` mode to set up a recurring payment.
- We can't calculate shipping rates for the delivery address via Stripe Checkout, so we'll need to do that ourselves and then apply it to the purchase.
- (There is a [Orders API beta](https://stripe.com/docs/orders#open-orders) that I've enquired about getting access to, which would allow us to calculate shipping rates, but we can't rely on this for the initial release)

#### How we can do this

So, to determine the shipping rate, we can:

1. Configure per-country shipping rates in the CMS. This could be done like Shopify: create a "shipping zone" that applies to a range of countries, with a shipping rate attached.
2. Ask users for their country / "shipping zone" before checkout
3. Create a price for the product they've picked, that includes the relevant "shipping zone" rate.

We could potentially add the shipping rate [as a second product subscription](https://stripe.com/docs/billing/subscriptions/multiple-products) instead of factoring it into the primary subscription price, but I feel that might confuse things down the line with things like cancellation and pausing subscriptions.

**Comment by janbaykara** [comment]
Some questions back to you @melaniepatrick:

- Shall we move forwards with the shipping zone selector? This means that products will have UK, EU and ROW prices.
- What the rationale is to stop people from cancelling for the first three months, if shipping rates are included in the subscription price?
  - I think we would have to communicate this up front if they are locked in.
  - This might be technically possible, but it will complicate things and I'm concerned for us to make progress on other fronts before launch.

**Comment by janbaykara** [comment]
So I reckon we could actually just define per-zone shipping prices for each product. 

E.g. the Solidarity product might have the following prices defined:

- (Monthly) UK: £20
- (Monthly) EU: £24
- (Monthly) ROW: £30
- (Annually) UK: £200
- (Annually) EU: £240
- (Annually) ROW: £300

Then based on the country selector we can select the right pricing. We'll have a simple 'shipping zones' thing in the admin panel so you can decide what these codes are.

<img width="453" alt="Screenshot 2022-03-31 at 09 01 42" src="https://user-images.githubusercontent.com/237556/161006940-5b205995-b575-4638-b8cb-b25953e33a34.png">

**Comment by melaniepatrick** [comment]
great
I agree probably not wise to disallow it, though good to know that is an
option in future

**Comment by melaniepatrick** [comment]
> ### Solidarity pricing
> So the current prototype asks the user on one question at a time ([an accessibility design principle](https://designnotes.blog.gov.uk/2015/07/03/one-thing-per-page/)). First: what plan? Second: solidarity? Third: password. Fourth: payment.
> 
> [(Screenshot)](https://user-images.githubusercontent.com/237556/160931783-5fb4d505-56cf-4bfc-80e7-fc4a851ec1f0.png)
> 
> This is similar to how [GoodGym](https://goodgym.org) does it: you pick the 'donation level'. The difference is that GoodGym doesn't have different products to sell, just the one membership, so they don't need to worry about too much.
> 
> [(Screenshot)](https://user-images.githubusercontent.com/237556/160982329-4457059f-062c-4688-acb7-2c72098771a2.png)
> 
> Anyway, what you're suggesting in the doc is to have "solidarity" as one of the three options, which as you say makes it more prominent, and to not have a second 'donation level' step. I think is an elegant solution and we should do it that way instead ✅

Ok, if you think that works then let's do it. So they will have 3 options to choose from initially. If they pick 'Selected Books' (ie 6 books) we will then need to ask them at a second stage whether they want Classics or Contemporary. So I guess it complicates that journey slightly.

**Comment by janbaykara** [comment]
> If they pick 'Selected Books' (ie 6 books) we will then need to ask them at a second stage whether they want Classics or Contemporary. So I guess it complicates that journey slightly.

Ah, I overlooked this. I think this is going to complicate things for the initial launch. Could we include the two book series as separate options? They could be styled submissively so as not to take up lots of space.

**Comment by melaniepatrick** [comment]
> Some questions back to you @melaniepatrick:
> 
> * Shall we move forwards with the shipping zone selector proposal [in the comment above](https://github.com/commonknowledge/leftbookclub/issues/10#issuecomment-1084097779)?
> * For the initial discount for shipping-included plans, is the rationale here to "waive" the shipping cost, or something else? We can definitely add a three month discount coupon to subscriptions, but I'm curious about the intention so that I can figure out how to relate the configuration to the communication.
> * What the rationale is to stop people from cancelling for the first three months, if shipping rates are included in the subscription price?
>   
>   * I think we would have to communicate this up front if they are being locked in.
>   * This might be technically possible, but it will complicate things and I'm concerned for us to make progress on other fronts before launch.

It's a real shame we can't configure the shipping price separately in Stripe. But I understand your reasoning on this so yes it sounds like we should move ahead.

Having thought about the discount issue, I think we should drop it. I feel it is overcomplicating the presentation of the plans and it does not work with the idea of running discount codes. We want to be able to run special time-limited offers using codes. Rather than a continual discount. 

So I propose that we present plans without a discount but obviously we have to include shipping in the product price in Stripe. But I would like to find a way of presenting that to people that makes it look like the shipping is separate. Because I don't want it to look like we have raised our prices. I just want it to look like the price is still £9.99 but then they have to pay shipping as a second stage.

This is what we do now on the current website.

**Comment by melaniepatrick** [comment]
So that sounds like we can set postage separately then? Rather than within
the Stripe price?
I think I need to talk this through with you, as I'm not quite following.

**Comment by melaniepatrick** [comment]
If we don't do the discount we don't need to do the thing where we prevent
them cancelling either. And yes we would have to always let them know.
But I would like the option to be able to start doing this in future, if we
think it's a good idea.
As long as I have a fully editable page where people sign up, then I can
add this kind of information to it?
