### ISSUE TITLE
Add remaining blocks to homepage

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#112]

**Comment by janbaykara** [comment]
@melaniepatrick I've deployed the latest changes and added some content blocks that can be used to compose the homepage. You can see an example of this at the stagin site right now: https://lbc-staging.fly.dev/

See if you can log in and edit the "Left Book Club" home page, and play about. At our call in the late afternoon (4pm still good?) we can walk through using the CMS in this way.

**Comment by melaniepatrick** [comment]
Yes 4 is good, thanks Jan.
