### ISSUE TITLE
Enable shipping discounts for UK annual prices

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#114]
On interval=year prices, where zone includes UK, shipping fees can be waived, but this might change in future.

We need a way to toggle this from the plan creator UI.

Potentially this could be a config option on the MembershipPlanPrice model:

`free_shipping_zones = models.ManyToManyField(ShippingZone, multiple=True)`

**Comment by janbaykara** [comment]
@melaniepatrick UK shipping discounts for annual plans has now been deployed. Here's how it works:

In the plan page [(e.g. solidarity plan)](https://lbc-staging.fly.dev/admin/pages/83/edit/?next=/admin/app/membershipplanpage/), under the prices section, you can now simply select which shipping zones if any for a price (e.g. the yearly price) should result in a shipping fee waiver.

<img width="876" alt="Screenshot 2022-04-29 at 08 32 22" src="https://user-images.githubusercontent.com/237556/165902217-df71855a-1ab9-4719-928f-506f2c8f699d.png">
 
The shipping billing line remains, at 0, so that in the future if required we can upgrade the shipping price on their subscription.

**Comment by melaniepatrick** [comment]
great! Nice way of doing it, and flexible for future. Thanks.
