### ISSUE TITLE
Add "autorenew" label throughout the checkout

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#121]

**Comment by melaniepatrick** [comment]
ok so I've tried to find examples I think are pretty good about making it clear. It's not just the fact we need to say it auto-renews during the checkout process.  But also the fact that we are billing monthly or yearly, could be slightly clearer than it is now.
Question: at the moment I can edit the price in a subscription but not the part afterwards ('/month' or '/year'). That might be good to change to '/billed monthly' and '/billed yearly' -- like gal-dem does in the example below. It implies recurrence.

![Screenshot 2022-04-29 at 18 27 59](https://user-images.githubusercontent.com/100857719/166116523-ceac1023-8579-4a42-9227-e6509016
![Screenshot 2022-04-2
![Screenshot 2022-04-29 at 18 31 31](https://user-images.githubusercontent.com/100857719/166116572-306793e2-f3f9-475c-8fcf-1de4f527016f.png)
9 at 18 31 17](https://user-images.githubusercontent.com/100857719/166116568-457889f8-9f7c-4a63-a9d6-f660b3626052.png)
f17a.png)
![Screenshot 2022-04-29
![Screenshot 2022-04-29 at 18 31 05](https://user-images.githubusercontent.com/100857719/166116564-cc652589-2402-4624-8bd2-41512c999669.png)
 at 18 30 59](https://user-images.githubusercontent.com/100857719/166116551-5e8d8562-083e-406f-bd61-386d2291bbb7.png)

**Comment by melaniepatrick** [comment]
![Screenshot 2022-04-29 at 18 27 59](https://user-images.githubusercontent.com/100857719/166116651-09e6cecb-3e19-4f1e-ae8b-9f4947e0b269.png)

**Comment by melaniepatrick** [comment]
![Screenshot 2022-04-29 at 18 31 05](https://user-images.githubusercontent.com/100857719/166116804-9ee0d583-34a1-44e4-abc2-a67e0a9355ed.png)

**Comment by melaniepatrick** [comment]
![Screenshot 2022-04-29 at 18 31 31](https://user-images.githubusercontent.com/100857719/166116830-76970656-8076-45e7-8f9c-47c00734a4f8.png)

**Comment by melaniepatrick** [comment]
If the gal-dem text is too long (ie specifying the date it renews) we could say something simpler like:
'Membership payments automatically renew, but you can cancel at any time.'

In general I am trying to avoid the word 'subscription' as I've noticed some successful subscription based sites tend not to mention it at all and just focus on what it is that they are offering. It may not always be possible but if we can it would be nice.
