### ISSUE TITLE
Image uploads don't work

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#124]
- [ ] Staging
- [ ] Production

**Comment by janbaykara** [comment]
Wonder if this is a DO Spaces config error.

**Comment by chrisdevereux** [comment]
The `AWS_S3_ENDPOINT_URL` was set incorrectly (was: https://lefbookclub.ams3.digitaloceanspaces.com rather than https://ams3.digitaloceanspaces.com).

This is now confirmed working.

**Comment by janbaykara** [comment]
CC @melaniepatrick, image uploads should now be working.
