### ISSUE TITLE
Update book page styling

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#148]

**Comment by melaniepatrick** [comment]
Some feedback here. I like Gemma's layout that goes straight into the book of the month with no text at the top. I don't quite follow how the live site is currently configured. I'd like to remove the requirement to have text at the top.

**Comment by janbaykara** [comment]
What do you mean by text at the top?

**Comment by melaniepatrick** [comment]
Sorry, this is the Books overview page, not an individual book page. 
This is not urgent, I just wanted to note it for fixing at some point.
At the moment it shows the book of the month, but I can't find that set up in Wagtail.
There is simply a text box, for title and text. You have to fill in both (it's required). I would like it to be optional. 
For instance, I don't think we need a title for this page at the top (Books).
We can just have a short paragraph of text, which I've added. Then go straight into the book of the month.

**Comment by janbaykara** [comment]
I get you now. I'm going to change this so that you can configure it like that, as with other pages, using the "Featured Book" and "Book Grid" options.
