### ISSUE TITLE
Migrate copy from the following pages:

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#157]
- [ ] https://www.leftbookclub.com/
  - [ ] Homepage
  - [ ] History
  - [ ] Groups
- [x] https://www.leftbookclub.com/events
- [ ] https://www.leftbookclub.com/partners
- [ ] https://www.leftbookclub.com/about
- [x] https://www.leftbookclub.com/terms
- [x] https://www.leftbookclub.com/contact
- [x] https://www.leftbookclub.com/faq
- [x] https://www.leftbookclub.com/privacy

**Comment by janbaykara** [comment]
@conatus, @melaniepatrick is happy to take this but appreciate if you can stay on standby in this issue.

**Comment by conatus** [comment]
Cool. Consider me on standby!

**Comment by melaniepatrick** [comment]
thanks!
