### ISSUE TITLE
Migrate gift recipients into Stripe, on pre-paid subscriptions

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#16]
Customer creation is handled by #78 already.

What we need to do is a second import operation based on this query:

```sql
SELECT
    g.id as "gift_id",
    g.code as "gift_code",
    us.user_id as "giving_user_id",
    gifters.email as "giving_user_email",
    giftsub.stripe_id as "giving_sub",
    giftsub.stripe_status as "giving_stripe_status",
    g.email as "initial_recipient_email",
    recipients.id as "recipient_user_id_matching_gift_email",
    recipientsub.stripe_id as "follow_up_recipient_sub",
    recipientsub.stripe_status
FROM gifts g
LEFT JOIN user_subscription us ON us.id = g.user_subscription_id
LEFT JOIN users recipients ON recipients.email = g.email
LEFT JOIN users gifters ON gifters.id = us.user_id
LEFT JOIN subscriptions giftsub ON giftsub.user_id = us.user_id
LEFT JOIN subscriptions recipientsub ON recipientsub.user_id = recipients.id
ORDER BY giftsub.stripe_status, g.id;
```

- [x] Set up an import function for a CSV based on the above query:
  - [x] Convert gift codes into promotion codes
  - [x] Mark the gift giver subscriptions with the relevant metadata (`gift_mode=True, promo_code=X`)
  - [x] Check for where a recipient user exists + the gift giver subscription is active + the recipient user doesn't already have a **non-gift_mode** subscription
    - [x] If true, then create a gift recipient subscription for the recipient using this promo code modelled on the giver subscription with relevant metadata

**Comment by janbaykara** [comment]
Just making some notes here for myself:

### (How many) gift subscription customers to create

- There are no users who've redeemed a gift, who have a `stripe_id` (customer)
    ```
    SELECT *
    FROM user_subscription_histories h
    JOIN users u ON u.id = h.user_id
    WHERE activity LIKE "Gift%"
    AND stripe_id IS NOT NULL;
    ```
- 225 records show up here, so that's the number of new gift subscriptions

### How to link gift subscriptions to their gift recipient?

- We want to use the same metadata structure as in the new codebase, so that we don't need special logic.
  - Gift giver subscription metadata:
      `{ "gift_mode": "True", "promo_code": "promo_..." }`
  - Promo code generated for redemption:
      `{ "gift_giver_subscription": session.subscription, "related_django_user": self.request.user.id }`
  - Gift receiver subscription metadata:
      `{ "gift_giver_subscription": "sub_...", "promo_code": "promo_..." }`

So when we create a new gift subscription for these 214 people, we need to:

- Find out who their gift giver is, and apply the correct metadata on their subscription
- Create the promo code
- Creat the gift

We can probably (ideally) use the same code that we use to do this on the fly, to run this retroactively in a batch process.

### How to identify the gift_giver subscription to start this process off

We need to know which subscription is paying for the gift receiver. We have one obvious clue: we know who has redeemed a gift. Perhaps this is referenced elsewhere?

- This gets us the subscription product that the recipient wants to be on, but doesn't maybe say where it came from:
    ```
    SELECT user_id, subscription_type
    FROM user_subscription_histories h
    JOIN users u ON u.id = h.user_id
    WHERE activity LIKE "Gift%"
    AND stripe_id IS NULL;
    ```

Database diagram to help figure this out:

<img width="609" alt="Screenshot 2022-04-29 at 12 36 21" src="https://user-images.githubusercontent.com/237556/165937157-6f23eee8-f622-442f-a366-0676c221b941.png">

Doesn't really reveal anything. I've emailed Fergus for clarification.

**Comment by janbaykara** [comment]
@melaniepatrick is it possible for someone who's bought a gift subscription to also buy themselves a normal membership subscription, with the same account? Or do they currently have to register a second user to do so?

**Comment by melaniepatrick** [comment]
at the moment you can only have one subscription linked to each account.
So they have to buy a second subscription under a different email address.
Am very pleased we will be changing this as it often leads to confusion!
