### ISSUE TITLE
Migrate customers to new subscription products

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#161]
Some old LBC customers are on a generic stripe product (something like "Left Book Club Membership Subscription"), but are actually on different book delivery plans that Stripe doesn't know about.

This makes fulfilment tricky and things are a bit ambiguous.

We can update these customers' stripe subscriptions to express the product that they are actually on.

We can also do this for the batch of customers on 2020* products.

**Comment by melaniepatrick** [comment]
Hi Jan
I've noticed that the migration of old members onto new products has hit an issue somewhere. I checked a few, which looked, fine, but our monthly recurring revenue jumped by over £1000 in one day -- June 9th. Some customers must have been migrated to a product where they are paying more? We need to find which ones and sort this out before any more invoices go through. Let's discuss tomorrow -- I'll send a screenshot via email.

**Comment by janbaykara** [comment]
Example gift recipient here: https://dashboard.stripe.com/subscriptions/sub_1L6ByjKYdS0VccAEM8tB22xz

**Comment by melaniepatrick** [comment]
Great thanks. The MRR hasn't changed yet but I'm hoping that's just because Stripe can take a while for updates to go through and hopefully it will correct tomorrow.

**Comment by janbaykara** [comment]
Yes it's the 14th now and the graph is only showing the 12th, so I think we'll get a better view by Thursday or Friday.

<img width="474" alt="Screenshot 2022-06-14 at 10 43 33" src="https://user-images.githubusercontent.com/237556/173547558-9cb83eed-ac11-41bb-9bea-23ea1b3a1d6f.png">

**Comment by melaniepatrick** [comment]
cool thanks
