### ISSUE TITLE
Facebook ad tracking

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#183]

**Comment by janbaykara** [comment]
Hi @melaniepatrick. Can you confirm whether jan@commonknowledge.coop has been invited to the Facebook Business team? I'm having a bit of trouble logging in.

**Comment by janbaykara** [comment]
This will be going live shortly.

**Comment by janbaykara** [comment]
I also added sale price to the tracking, to help the algorithm out a bit.

**Comment by melaniepatrick** [comment]
THanks. It would be helpful to quickly go over the Facebook set up so I can make sure I am setting it up correctly to function with our ads. Basically now the website has changed I assume I will need to make a new 'subscribe' event, to track conversions? But it does mention an API for tracking conversions also. So before I spend more money on facebook I'd like to clarify best practice for what I'm doing.

**Comment by janbaykara** [comment]
I've configured the `Subscribe` event to fire automatically when payment is complete, so you shouldn't have to do anything around events.

**Comment by melaniepatrick** [comment]
Ok thanks. That's great.

I had an ad running previously which was trying to get conversions based on
the 'Subscribe' event I'd set up (somebody pressing the payment button).

Can I make that same ad live again? Will it be affected by the fact the
'subscribe ' event is now configured a different way? Should I just run a
new ad, with the new kind of 'subscribe' configuration?

**Comment by janbaykara** [comment]
Yes, you can continue using these adverts if they use the Subscribe "[standard event](https://developers.facebook.com/docs/meta-pixel/implementation/conversion-tracking/)", as these are events defined by Facebook. Only the way that the event is logged -- on the website -- has changed :)
