### ISSUE TITLE
Map of members and reading groups

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#189]
- See members near you
- See / join reading groups near you
- Facility to propose / start up a reading group with nearby people

**Comment by janbaykara** [comment]
@melaniepatrick the Circle events list/map is live! https://leftbookclub.com/events/

**Comment by melaniepatrick** [comment]
this is so amazing!! Thanks!!

**Comment by melaniepatrick** [comment]
Also, working late Jan??? Hope you have a good friday off!
