### ISSUE TITLE
User login issue

### ISSUE THREAD

**Issue by melaniepatrick** [commonknowledge/leftbookclub#192]
Today after putting in email and password just get an error message: ‘forbidden 403’ or some such message.
Have tried using different browsers without success.
Best wishes
Stuart McGrath  stuart.mcgrath@hotmail.com

**Comment by melaniepatrick** [comment]
Libby Stone also having a problem logging in
lgstone@btopenworld.com
Is there some kind of wording I should give them to explain what to do to get it working?

**Comment by melaniepatrick** [comment]
Stuart McGrath comment that although he can now login
'it does state ‘not secure’ on top left of browser.'
wanted to pass that on.

**Comment by melaniepatrick** [comment]
How do we set up new admin accounts? For instance, the old login we had for the admin isn't working? I'd like Donus to have an admin account under the office@email address.

**Comment by melaniepatrick** [comment]
So I just watched a video of a user on Posthog.
 User 3F0D4
He's on for 10 minutes. He puts in his details to open an account. he puts in a password. But each time he seems to lose his password before he presses the button? He does this twice? Visually it looks to me like it could be some kind of error but see what you think?

**Comment by janbaykara** [comment]
Just linking the relevant recordings here for future reference: https://app.posthog.com/person/18096eaf3ef17d-07d73936a4580a-26f4961-fa000-18096eaf3f0d4?filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222022-04-30%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list#activeTab=sessionRecordings&sessionRecordingId=18099ee5fae1cd-02abd1eeda8e5f-26f4961-fa000-18099ee5faf1d2

I've watched the recording and can't make head nor tail of it. There is no special javascript going on in this page, so my instinct tells me it is a browser / local machine issue, perhaps affected by extensions or something. There's a world of possibilities. One thing I can say is that their browser is Chrome v100, which is only a few days old, so incompatibility isn't going to be a problem.

I've installed additional error tracking on the frontend/javascript side of the application to try and capture some more detail about this situation, in case it occurs for more than one user. Let's loop back to this if it comes up again.

**Comment by melaniepatrick** [comment]
thanks
