### ISSUE TITLE
Migrate existing subscribers from the generic `Left Book Shop Subscription` product to new fulfilment-oriented products

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#193]
The product in question: https://dashboard.stripe.com/products/prod_DctmmNsQ5TOdQC

- Use the historical app database to match the DB-based subscription type to the new products
- For each customer subscription for this product, replace the product/price

**Comment by janbaykara** [comment]
@melaniepatrick just to confirm that the fulfilment plan for this month is that you'll use the existing spreadsheet for customers on the old product, and no technical changes are required right now?

I think the long term solution is to silently migrate these old product subscriptions onto the current products with the same pricing. This might actually turn out to be quite a trivial thing to do.

**Comment by janbaykara** [comment]
Discussion today:

- We agreed to migrate old subscription products over to new products, for ease of fulfilment
- We'll keep everyone on the same price / billing schedule and simply update the product that the price refers to. This might involve duplicating the price data.
- This should result in no change of billing for the user.

**Comment by janbaykara** [comment]
@melaniepatrick status report: I'm about halfway through writing the script for migrating customers from the old products to the new products on stripe, to make fulfillment export files 'complete'.

It's getting late in the day and the end of the week, and I need to head off for the evening.

Would we be able to cover the migrating the legacy stripe products to the new stripe products on Monday, or is that really too late?

**Comment by janbaykara** [comment]
@melaniepatrick the migration of Stripe subscriptions to the new products is now under way. You'll see from this screenshot that in the next invoice (whose date is the same as before) the product switchover happens without any change to pricing:

![Image](https://user-images.githubusercontent.com/237556/172831581-015a9af1-e03d-46ce-94f3-c5a1607de13f.png)

https://dashboard.stripe.com/subscriptions/sub_1K5qhlKYdS0VccAEbQQDanAA

**Comment by janbaykara** [comment]
Migration is complete except for:

- [Customers like this](https://dashboard.stripe.com/subscriptions/sub_1KvMhIKYdS0VccAEEMwevIvM) who had gift recipient subscriptions set up for them manually as part of the website migration.
  - [ ] Switch them onto a new product based on the gift giver subscription product
  - [ ] Apply the relevant Gift Card for that new product
- Transition remaining Gift Card subscriptions to the new Gift Cards

**Comment by janbaykara** [comment]
Hi again @melaniepatrick.

OK, all members are now migrated over to the new products.

The fulfillment export spreadsheet has all the required columns, and I've confirmed that download is working reasonably fast.

You should now be able to download the full list of active members for delivery purposes. Please create new Github issues for any further fulfillment issues.

Cheers and have a good weekend!

**Comment by melaniepatrick** [comment]
Thanks Jan
I've just had a look at the excel download and I have a question that it
would be useful to sort out on Monday. When I download all active
subscribers there are a lot more than I expected. 1237. Whereas Stripe
tells me we have 1190 active members.

Are we perhaps including gift buyers in this list?

Have a good weekend, we can sort out next week.
thanks
Mel

**Comment by janbaykara** [comment]
@melaniepatrick [Stripe's definition of "active subscribers"](https://support.stripe.com/questions/understanding-active-subscribers) does not include recipients on gift card plans:

> How are Active Subscribers calculated?
> Subscribers are counted as “active” if they have at least one subscription that is "active". We count any subscription as "active" for which at least one invoice has been paid and which are in the status=active and status=past_due states. 

Gift recipients will not ever have had an invoice paid, as they aren't billed for any amount.

**Comment by janbaykara** [comment]
@melaniepatrick also, we are explicitly filtering out gift giver subscriptions from this list, so they do not show up in the export:

https://github.com/commonknowledge/leftbookclub/blob/889313043900a9007db4c2fe8a851ca4fd621f1e/app/wagtail_hooks.py#L141-L146

**Comment by melaniepatrick** [comment]
That's correct, thanks.
Yes going forward that could work.
