### ISSUE TITLE
Add `layout` copy to MembershipPlanPage

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#194]
When visitors click on a membership plan, they're currently taken straight to the checkout, where we're seeing a fairly high bounce rate. Alternatively when the plan has multiple products attached (for example, [selected books](http://leftbookclub.com/selected-books/), they're taken to the plan page. But it doesn't have any more info than the initial plan picker.

- [ ] Let's add `layout` to allow "more info" style marketing for plans.
- [ ] Let's redirect all "select" buttons to the plan page for this additional marketing OR place the additional marketing on the checkout page.

**Comment by janbaykara** [comment]
@melaniepatrick thoughts on this?

**Comment by melaniepatrick** [comment]
Agree

Let's get 'Select' to take them to the plan page. And we can drop 'learn more'?
And yes please make the plan page fully editable, that would be great.
I think this is probably better than putting it in checkout? Tempted to make checkout incredibly simple and maybe just a photo of the books, the name of the plan and nothing additional to read? Might be slowing people down.

ALSO: I think they are not expecting postage to be added and we should be more upfront about that. 
We could perhaps say '£9.99 / month + postage' on monthly plans right from the start?

what do you think?

**Comment by melaniepatrick** [comment]
Also not sure if you saw my point on the other thread about someone who was trying to sign up and seemed to keep losing the password they entered? User 3F0D4
I watched the video yesterday. They put the password in twice, and each time it seems to disappear when they scroll slightly. Is it possible there is a bug on the account set up page?

**Comment by melaniepatrick** [comment]
One other thing:
On the account set up page, rather than mentioning the word 'account', can we say something more informal like:
'Let's get you set up'

And then maybe a couple of bullet points:
* Radical books, direct to your door
* Cancel your membership at any time

**Comment by janbaykara** [comment]
The plan picker now directs visitors to the plan pages, which are fully editable. We've added a postage label and added "Let's get you set up" where I think you were talking about.
