### ISSUE TITLE
Final data migration

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#195]
- [x] Export CSV of new users since 29th
- [x] Run sync script
- [x] Export CSV of new gifts since 29th
- [x] Run sync script

**Comment by janbaykara** [comment]
Other cause of #192

**Comment by janbaykara** [comment]
@melaniepatrick all users and data from the old website (user logins and gifts since 29th April) have now been imported.

**Comment by melaniepatrick** [comment]
thanks!
