### ISSUE TITLE
Replace "your book is on its way" with a welcome message field

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#198]

**Comment by janbaykara** [comment]
This will be deploying shortly @melaniepatrick. It looks a bit like this:

<img width="1231" alt="Screenshot 2022-05-07 at 21 49 03" src="https://user-images.githubusercontent.com/237556/167271399-c546d6a9-0b3d-44ed-b552-1dfb4d71c5d3.png">

The top title is hardcoded, and so is the membership card confirming their subscription. Then, everything underneath that is configurable. You'll find that it's the same page builder options as for all other pages.

To edit the welcome message, go to /admin > `settings` > `Membership Journey` and then edit the `welcome content` as per normal. Let me know if that makes sense!

**Comment by melaniepatrick** [comment]
Thanks. I have gone to settings but I can't see Membership Journey within
that?

**Comment by janbaykara** [comment]
This is now live! https://www.leftbookclub.com/admin/settings/app/membershipjourney/3/

You can demo what it looks like by visiting https://www.leftbookclub.com/welcome/
