### ISSUE TITLE
Fix Facebook event tracking

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#230]

**Comment by janbaykara** [comment]
It's possible to reimplement the facebook tracking on the serverside, if we can find a way to identify the user: https://developers.facebook.com/docs/marketing-api/conversions-api/using-the-api

**Comment by janbaykara** [comment]
@melaniepatrick there was a bug with the Facebook pixel tracking that I've now fixed and verified that we're now receiving Subscribe events through Facebook's test center: https://business.facebook.com/events_manager2/list/pixel/2382372982013015/test_events?business_id=314547615929514&global_scope_id=314547615929514&nav_source=flyout_menu

You can begin using the Subscribe event now.

**Comment by melaniepatrick** [comment]
excellent thank you!
