### ISSUE TITLE
Menus cannot be edited because wagtailmenus doesn't support Wagtail 3.0

### ISSUE THREAD

**Issue by melaniepatrick** [commonknowledge/leftbookclub#243]
Hi Jan, I can't currently edited the footer or the menu. When I click on edit I just get an error screen. I need to add a partners page and a patrons page? If you could fix at some point that would be great thanks.

**Comment by janbaykara** [comment]
Hi @melaniepatrick. Yep, seen. There is a bug with the package we're using to manage menus (https://github.com/jazzband/wagtailmenus/issues/421#issuecomment-1133965025). If you post the menu details you need to change I can manually make these changes via the database, and will make a patch for this menu code shortly.

**Comment by melaniepatrick** [comment]
Thanks Jan

So I'd like to put a Patrons page in the footer basically.

It should say:

We would like to thank the organisations that have supported us.

And then show 3 logos -- Barry Amiel and Norman Melbourne, Lipman Miliband
and Pluto Educational Trust. I am attaching one here. I can look out the
others.

I can always put this up at the end of the week, it doesn't have to be
today.

thanks
Melanie

**Comment by melaniepatrick** [comment]
It would be good to get this sorted soon as I need to get the logos up before next week please. Thanks.

**Comment by janbaykara** [comment]
OK, I've thrown up a page with the required content [here](https://leftbookclub.com/patrons/) and added a link to the menu footer.

Hopefully in the next few weeks the menu plugin will be back in action. I'm sorry about this — Wagtail upgraded to 3.0 and the menu package is just lingering behind with a few minor updates to be done by their maintainers.
