### ISSUE TITLE
stripe account status issue

### ISSUE THREAD

**Issue by melaniepatrick** [commonknowledge/leftbookclub#247]
Just had a  member get in touch saying he is getting emails from stripe about updating his card details (his card was cancelled). Normally Stripe retries a customer's card five times, and on the fifth occasion it is automatically cancelled. During the process of retrying the card, the account remains active. This means members can still be treated as active members, and have a bit of time to complete their card update if they wish to.

In checking this account, I can see the status on Stripe is 'overdue' (I had never noticed this as a status option before, previously it was just either active or cancelled). I am wondering how this affects the member's website account and their member status. The guy who got in touch says that 'he got a message saying he was no longer a member'. I don't know exactly what he means by this. When he logs in, will it tell him his account is still active, or cancelled?

Screenshot of his message -- I will email this to you

**Comment by melaniepatrick** [comment]
and another. member saying the same thing. His card has failed once and the website is telling him he's not a member. I hadn't recreated this scenario in testing but it would be good to make it really easy for them to update their card info without going through checkout again? Shall I just tell him to go through checkout for the moment? (he doesn't want to cancel).
(emailing you screenshot)

**Comment by janbaykara** [comment]
We evaluate a user's `is_member` property based on whether their subscription exists and has `active` status [(based on this code)](https://github.com/dj-stripe/dj-stripe/blob/e5a34a107402dcaf418298d77cb9629c35a942a9/djstripe/models/core.py#L1161-L1170).

So in both of the cases you mentioned, we'll suddenly evaluate them as `is_member = False`. This does seem a bit sudden!

The possible statuses of a subscription are:

https://github.com/dj-stripe/dj-stripe/blob/e5a34a107402dcaf418298d77cb9629c35a942a9/djstripe/enums.py#L747-L754

Maybe we expand the list of `is_member` statuses to
- trialing
- active
- past_due
- unpaid

We could also add a banner (kind of like the "you didn't finish signing up" banner) to the website underneath the header with any subscription status info that isn't `active`? So for `past_due` we could say "Your membership payment is past due. Please check your payment details <here> [link]".

**Comment by melaniepatrick** [comment]
Yes thank you. I agree. Let's expand their member = true status to include those four possible options.
(By the way this list is slightly different from what I can see in the status options in the subscription area, but it probably amounts to the same thing: https://dashboard.stripe.com/subscriptions?status=past_due)

And yes I agree, we should add a message for past due and unpaid, (but not for trialing?). 

I imagine that when they sign in, it would feature their subscription in the usual way. So it's clear that they are a member. But the warning message about updating payment details would sit below that?

I like your suggested wording. If they are easily able to click and then immediately update their card payment info that would be good. The less they have to do, the better.

Thanks.

**Comment by janbaykara** [comment]
So we now have these kinds of banners and badges for various member statuses, that link to relevant actions:

<img width="630" alt="Screenshot 2022-06-02 at 17 36 02" src="https://user-images.githubusercontent.com/237556/171683796-04043cb7-b3bf-4ff0-8962-4c973da5cf47.png">
<img width="698" alt="Screenshot 2022-06-02 at 17 33 18" src="https://user-images.githubusercontent.com/237556/171683801-38159c5e-f7a7-4957-b1fc-b0c90597711f.png">
<img width="821" alt="Screenshot 2022-06-02 at 17 52 03" src="https://user-images.githubusercontent.com/237556/171683787-ab3f3349-7894-4403-a6b5-52e54d562e05.png">
<img width="437" alt="Screenshot 2022-06-02 at 17 49 12" src="https://user-images.githubusercontent.com/237556/171683793-f8aa1473-e321-4c55-8888-638ec0702e28.png">
