### ISSUE TITLE
direct debits in Stripe

### ISSUE THREAD

**Issue by melaniepatrick** [commonknowledge/leftbookclub#249]
I signed up for a direct debit account out of curiosity, and it looks like Stripe sends automated emails to remind people their account will be debited, before payment is taken.
I long ago turned off these kind of reminders for card payments, and I might look into doing the same for the direct debit payments. I just wanted to ask if you remember setting any info for this during the process of creating the direct debit payment facility in Stripe. I can look into it, so no big deal.

**Comment by janbaykara** [comment]
I don't remember touching any settings around automated emails, no.

**Comment by melaniepatrick** [comment]
ok thanks.
