### ISSUE TITLE
Prep for New Member Meetup facilitation

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#273]
- Discussion: https://mail.missiveapp.com/#inbox/conversations/ea335b19-175c-46d1-ac80-be89c0ca892e
- Notes: https://mail.missiveapp.com/#inbox/conversations/b4c4dfe3-5118-4183-9190-882d9a1a689b

Set up an agenda basically.

**Comment by melaniepatrick** [comment]
Hi Jan, I've tried logging in with my pluto and lbc emails but nothing is showing. Sorry, I can't see the info here?

**Comment by janbaykara** [comment]
Thanks Melanie, looks good!

Depending on ~~vibes~~ during the call, we could also share some info about what's coming up 'next month' from an LBC perspective. For example, a quick thing about the new book, or other upcoming community / events stuff?

**Comment by melaniepatrick** [comment]
Sure, ok. Elif I guess you could talk a bit about upcoming events (the Bevins event, and the Race to the Bottom event?) and anything else you think it would be good to mention. David confirmed the book for August will be this: https://commapress.co.uk/books/protest-stories-of-resistance

**Comment by janbaykara** [comment]
### Learnings for the LBC service:

- "I'm falling behind but hope to catch up" on the books
- Receiving LBC books as an easy way to keep up with ideas, round out your knowledge
- People thinking about pedagogy in their own contexts: e.g. cocreation in universities

### Iterations for next time:

- Get people to share their recommendations and references and bibliographies and recommendations. Questions and favourite books.
- Do a second round after the "organising"/"thinking"/"questioning". Break the rounds for now.
- Frustrations / inspiration
- Do a time check at the beginning, do say the agenda
- Turn this into slides — more explicit structure — just simple title slides for the different segments
  - As Riley said, can be more inclusive / accessible
- Link out to relevant resources
- Can we ask people to volunteer explicitly (as a welcome call facilitator, a local reading group facilitator)
- Maybe add a themed discussion segment (we talked about this on Monday @melaniepatrick)
  - The latest book, for example 

### For the forum:

- Put the agenda in the event post
- Post a summary of the call on Circle.so
- Do a regular poll on thematics for new syllabi / books / discussions
- Maybe record this next time! Or just the events section, Elif is really good at the summary

Any post-meet reflections @melaniepatrick / @ElifSarican?

**Comment by melaniepatrick** [comment]
Thanks Jan. Great notes. Thanks so much for facilitating, you did a fabulous job. 
I think it might be good to try and get Amber to come along to the next one if we can -- she is organising the successful Manchester reading group. Having her there to share her experiences of what makes a group work could be very useful.
And yes we should think about a theme for next time.

**Comment by melaniepatrick** [comment]
And yes we can ask people at the beginning if they are happy for us to record it, or I can just record Elif's round up?

**Comment by janbaykara** [comment]
I think let's not record most of it as that might make people feel a bit 'watched' — but if they're up for:

- a quick screenshot of the gallery view, for posting to Circle
- 'interesting' notes from the call, like if anyone shared anything that others would find useful
- recording Elif's round up
