### ISSUE TITLE
Clarify who is actually paying Mailgun

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#312]

**Comment by janbaykara** [comment]
We sent an invoice to them but want to make sure the money is actually coming out of our account, not theirs.

**Comment by janbaykara** [comment]
Hi @melaniepatrick, @conatus informs me that we did end up paying for Mailgun, so the invoice related to that still stands.

**Comment by melaniepatrick** [comment]
ah ok, thanks. Is this a rolling cost? Should we put our own card on it?

**Comment by conatus** [comment]
@melaniepatrick 

Yup - that would be cool. Have added another issue to track this over at https://github.com/commonknowledge/leftbookclub/issues/326 - I'll drop you an email over the next few day with instructons on how to do this.

Thanks!
