### ISSUE TITLE
Display other merchandise on the website

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#324]
- [ ] Synchronise ALL available Django-channel products
- [ ] Same template for product
- [ ] A new page for displaying merch products

**Comment by janbaykara** [comment]
@melaniepatrick the current merch site is very simple, layout wise. Maybe as a starting point we just use a grid-based layout for presenting the merchandise, and then re-use the book template (e.g. [this layout](https://leftbookclub.com/books/protest/)) for individual product pages? This should be easily doable.

<img width="1182" alt="Screenshot 2022-09-14 at 11 11 36" src="https://user-images.githubusercontent.com/237556/190126980-bed005ca-84d9-4d87-8b9d-f430701947e4.png">

**Comment by melaniepatrick** [comment]
exactly, perfect

**Comment by janbaykara** [comment]
OK, this is now live at https://leftbookclub.com/merchandise/ @melaniepatrick :)

**Comment by melaniepatrick** [comment]
thanks!
