### ISSUE TITLE
TWT (liverpool) event doesn't show up on the map

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#352]
- Circle event: https://community.leftbookclub.com/c/find-an-event/twt22-left-book-club-reading-group-the-power-of-protest
- Map page: https://leftbookclub/events

**Comment by janbaykara** [comment]
I've discovered the issue and will deploy this by tomorrow morning @melaniepatrick.

**Comment by melaniepatrick** [comment]
great thank you
