### ISSUE TITLE
Facebook Pixel isn't registering events

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#360]
> I'm just trying to set up a Facebook advert and there seems to be a problem with running it to get conversions. When I select 'subscribe' as my conversion objective it tells me there have been no conversion events recently? It worked fine back in June so not sure what is going on here? Screenshot attached -- any idea what's going on? Thanks.

![image](https://user-images.githubusercontent.com/237556/193549192-9bb21582-d2bd-48da-b452-4f2a98c05643.png)

**Comment by janbaykara** [comment]
This pixel (`2382372982013015`) does actually seem to be receiving results (see below screenshot). This is the same Pixel ID as you are using for your ads. I think that we need to configure the advert to optimise for the right kind of "event". @melaniepatrick could you share the URL to the ad page where you got that screenshot, so I can take a look?

FYI the pixel registered the following Web Events:

- `PageView` (self-explanatory — a visit to any page after the ad is clicked — configured via code [here](https://github.com/commonknowledge/leftbookclub/blob/45ac5a5f3b7da68c21f04e76f688026c92b1b90f/app/templates/base.html#L43))
- `InitiateCheckout` (when people get to the "pick shipping country" page — configured via code [here](https://github.com/commonknowledge/leftbookclub/blob/eef2ce43514e3033b82673b8654cc5dad36bbd38/app/templates/app/confirm_shipping.html#L5))
- `Subscribe` (when people complete payment and successfully buy a membership — configured via code [here](https://github.com/commonknowledge/leftbookclub/blob/8e8c9f1ad2d8566d9f63c717d7097f1bff1ead87/app/templates/stripe/checkout_success.html#L10))

<img width="449" alt="Screenshot 2022-10-03 at 12 21 52" src="https://user-images.githubusercontent.com/237556/193565212-f7baf511-ab74-4aac-98ed-dc42d225459c.png">

**Comment by melaniepatrick** [comment]
Thanks Jan. Facebook is very mysterious, sometimes I think it's just so
badly built as an application that it constantly seems to breakdown for no
reason.

This was the page view for the Ad Set I was creating.

I have just tried setting up another advert, creating a new Campaign/Ad Set
that I have called 'Autumn Winter free book conversion'. You can see it as
a draft.

The problem has now vanished. It let me select 'Subscribe' as the
conversion with no issue. Screenshot attached.

So the fact you looked at it seems to have caused it to remember it is in
fact collecting this data?

Very odd!

**Comment by janbaykara** [comment]
Odd indeed. I agree, the Ads app is horrendously flimsy. Closing out this issue :)
