### ISSUE TITLE
Circle 2.0

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#368]
[The Circle 2.0 visual refresh is ready to be activated](https://community.leftbookclub.com/features/visual-refresh). Shall we go for it @melaniepatrick @ElifSarican?

It seems to be a purely aesthetic update with some extra styling features. You can preview the thing if you want a bit of reassurance but from my point of view we're good to go. I'll leave it with you to decide!

**Comment by melaniepatrick** [comment]
Yes I think we should probably do this, though if it's going to take time
it's not a priority. If it's really simple & quick happy to go ahead!

**Comment by melaniepatrick** [comment]
let's do it!

**Comment by janbaykara** [comment]
It's live!
