### ISSUE TITLE
fix formatting of email news sign up box [LBC-252]

### ISSUE THREAD

**Issue by melaniepatrick** [commonknowledge/leftbookclub#406]
Would really like to get this on the homepage but the formatting is weird at the moment, can we tweak it?

**Comment by janbaykara** [comment]
I'll add this to the backlog for next cycle!

**Comment by janbaykara** [comment]
Comment from [Linear (#252)](https://linear.app/commonknowledge/issue/LBC-252/fix-formatting-of-email-news-sign-up-box-commonknowledgeleftbookclub)

Brought up today at check-in meeting.

---
*via LinearSync*
