### ISSUE TITLE
Set up single sign-on

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#46]
We want to see how this works so that we can try SSO to Circle.so.

Options we have:

### Auth0

Using Auth0's [django integration](https://auth0.com/docs/quickstart/webapp/django/01-login) would allow us to log in to Circle as they have a native, free Auth0 SSO feature.

To make this work we need to ensure that 

- Inspect how this actually works in practice
  - With Django log in
  - With Circle.so log in
- We can port users over from the old website to Auth0 seamlessly, and tie the Auth0 user to the Django user which is related to their Stripe subscription (#16, #18)

### Django as an SSO provider

We can also use oauth-toolkit to set up our own SSO provider.

https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html

This means spending an additional $99/month ($1188/year) on Circle.so for the custom SSO integration.

But it might be smoother.

- See how this works with Circle.so

**Comment by melaniepatrick** [comment]
sure I just did that

**Comment by janbaykara** [comment]
<img width="861" alt="Screenshot 2022-06-15 at 18 49 46" src="https://user-images.githubusercontent.com/237556/173892638-c87ce72a-7b65-485d-b20a-16e22e21b306.png">

Bizarre, it says that the group has expired. Are you seeing that too?

**Comment by janbaykara** [comment]
OK, as a workaround, would you mind inviting hello@commonknowledge.coop also. I think because I set up a test community myself, it is confusing which community I am trying to access.

**Comment by janbaykara** [comment]
Good news! I have managed to demo on my local machine a "single sign on" from the web app to another test third party application, validating the possibility of doing this in production between leftbookclub.com and Circle.so.

Here's the demo video: https://www.loom.com/share/08f8b5d5b5ff48849d8058be388d7512

Next step would be me trying to demo this with the staging app (https://lbc-staging.fly.dev) and the LBC Circle.so community space. This would allow staging users to login to Circle via their membership login, and we can continue to allow admins to login separately to Circle.so through their Circle login. I can give you a demo of how this all works on Monday and then we can step forwards with our community planning.

So yes, please add hello@commonknowledge.coop to the admin list and we can proceed @melaniepatrick. Cheers!

**Comment by melaniepatrick** [comment]
ok I've done that

**Comment by janbaykara** [comment]
Good news! Single sign on now works. @melaniepatrick, you can try this out by logging out and then visiting community.leftbookclub.com again and logging in via Left Book Club, using your normal LBC login details — you can try different users to verify that this works for new folk.

As of now, Circle.so isn't linked anywhere on the LBC website, but we could look at adding a button in the member area for those who've been given access or something during this first trial phase. Additionally, we can just link people straight to community.leftbookclub.com in emails and so on.

**Comment by janbaykara** [comment]
As I say, we need to talk to Phillip about the pricing for this. It would be better to use this straight forward solution than moving all the user passwords to Auth0, and perhaps we can convince him to give us a discount.
