### ISSUE TITLE
Export all Books to Shopify collection

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#71]

**Comment by janbaykara** [comment]
Hi @melaniepatrick, some questions around importing books to Shopify.

- Some books don’t have prices
- Some books have `Published=False`

Do we want to import all books or only some, and if so, what is the rule of thumb?

**Comment by janbaykara** [comment]
Hey again @melaniepatrick. There seems to be a programatic way to import books-specific Metafields. I can export the basic products but would you mind going through and adding the Metafields for the books?

**Comment by melaniepatrick** [comment]
Sure, that's fine. Tell me exactly what you want me to add and where.
I can see the metafield tags.
You mean you will import the books as products and I will fill out the
metafield tags for each one?
That's fine. Let me know when you're done with importing the books.

**Comment by janbaykara** [comment]
No rush! I'll let you know when the books are up.

**Comment by janbaykara** [comment]
OK, handing this over to you Melanie. I've just gone ahead and imported the books; you can see them here: https://left-book-club-shop.myshopify.com/admin/products?saved_search_id=2325740257513

Things that need to happen next:

- [ ] Check the variants (hardcover, softcover, ebook, etc.), their prices, inventory count
- [ ] Add relevant metafields (ISBN, Author, etc.) A very important one is Published Date!
- [ ] Add the books we want to display to the "Django App" *channel*
- [ ] Add the books we want to display to the "Member-only books" *collection*

You can do the last two things from the list view as a bulk action (ticking multiple products and doing them at the same time):

<img width="469" alt="Screenshot 2022-04-26 at 11 38 16" src="https://user-images.githubusercontent.com/237556/165282339-cacf1a32-f292-4e40-8599-cd1eb374d577.png">

Cheers! Jan

**Comment by melaniepatrick** [comment]
great thanks Jan!

**Comment by melaniepatrick** [comment]
actually I've realised I just need to take out the dashes, seems fine now.

**Comment by melaniepatrick** [comment]
This is now done.

**Comment by janbaykara** [comment]
Great, these are now synced! Check it out at https://lbc-staging.fly.dev/books/
