### ISSUE TITLE
Move to alternative shipping plan

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#82]
https://github.com/commonknowledge/leftbookclub/discussions/59#discussioncomment-2599218

**Comment by janbaykara** [comment]
Almost done, remaining tasks:

- [ ] Ensure that address form updates the stripe customer

**Comment by janbaykara** [comment]
@melaniepatrick, over to you. Can you create the shipping zones + shipping rates that you need over here please: https://github.com/commonknowledge/leftbookclub/wiki#shipping-zones

If you create a zone with the code "ROW" and tick "rest of world", it will be the default shipping rate if the delivery isn't going to another zone.

**Comment by melaniepatrick** [comment]
Ok so I've chosen the countries for the EU shipping zone now.
All prices are correct.
UK: £2
EU: £6.50
ROW: £10
(we had 4 zones on the old website but US has now been put into ROW).

How are we handling shipping for annual subs?

**Comment by janbaykara** [comment]
Covering annual shipping in #102 (linked above), will show you on call tomorrow.
