### ISSUE TITLE
Coupons must work: I enable coupons / promo codes to be inputed

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#90]

**Comment by janbaykara** [comment]
When #108 is deployed, checkout will accept a promo code.

To make the current promo codes work, we just need to take the ID and add a customer-facing promotion code with the same ID. Would you mind sorting these out @melaniepatrick?

Demo video here just to be clear: https://www.loom.com/share/b62ccfe8fdc140fcbc7d472c5ab7ce5b

**Comment by melaniepatrick** [comment]
sure will do!

**Comment by melaniepatrick** [comment]
I've started making these in live mode.
I assume they won't affect how the current discount codes work on our
existing site?
I've accidentally given a couple of them the wrong expiry dates, but I
assume that won't affect the running of the current site as it isn't using
any data from this field?

Some of the questions in the promotion code box seem to duplicate questions
that are in the coupon already. For instance expiry date, number of times
it can be redeemed.
Do I need to do anything other than just save the code in this box, if I
have already set these perameters in the coupon area?

**Comment by janbaykara** [comment]
We agreed on the meet that, no, you don't need to tick any options on the promo code itself. So you can go through all of these coupons and migrate them to promotion codes without any change in logic.

**Comment by melaniepatrick** [comment]
Ok I've done them all in live mode now.
I haven't done any in test mode, but I guess we can just test it with the
one I created earlier?

**Comment by janbaykara** [comment]
That's right, yes
