### ISSUE TITLE
Gift subscription voucher redemption migration

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#91]
- See if there are many of these
- Maybe we can just do emails

**Comment by janbaykara** [comment]
@melaniepatrick, am I right in saying that the gift subscription vouchers are these ones here? https://www.leftbookclub.com/admin/vouchers

**Comment by janbaykara** [comment]
If that's the case, then:
- this part of the migration is very simple: all we need to do is create customer-facing promotion codes that use these voucher codes, set to 100% off "forever"
- It seems that there are 503 of these vouchers, but all but one of them are from 2019; only one is from 2022. So I'm not sure if we need to migrate all of them over?

I wonder if I'm looking in the wrong place for gift subscription vouchers?

**Comment by melaniepatrick** [comment]
you're correct, these are not our gift subscription vouchers!

**Comment by melaniepatrick** [comment]
As we have many things to go through I think gift subs could be parked for a while until we get the subscriptions themselves clarified?

**Comment by janbaykara** [comment]
Discussion reveals this is probably in the app database. I will check that, we'll probably have to migrate this manually.

**Comment by janbaykara** [comment]
So @melaniepatrick, what we're going to do for currently active gift subscriptions is migrate them over to the new system. There shouldn't be any problems: the codes that were generated will continue to work — I'll set them up as promotion codes, just like new gift codes will be. So no special action required for historical gift subscriptions.
