### ISSUE TITLE
UX / styling pass

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#99]
We should confirm how flows look, tighten things up, maybe make things look consistent, and sand any very rough edges.

**Comment by GemCopeland** [comment]
Just adding these here, but lmk if there's somewhere else I should put them.

I designed some page modules with image + text + CTA, as Melanie requested: https://www.figma.com/file/LPXoSWvicaddkI7xGlav7t/Design?node-id=14%3A472

So far there's a square version, a rectangle (shallower) version and one with a colour background and image treatment.

I've also designed the navigation now: https://www.figma.com/file/LPXoSWvicaddkI7xGlav7t/Design?node-id=207%3A1185

Let me know if you need anything else and feel free to assign me to tickets.

**Comment by janbaykara** [comment]
This is great, thanks so much @GemCopeland!

**Comment by GemCopeland** [comment]
I just noticed that those exports have lost their white space on the right, so look at the Figma as the source of truth.

**Comment by janbaykara** [comment]
Do we need a license to use adobe caslon pro, @GemCopeland?

**Comment by GemCopeland** [comment]
As mentioned on Signal, LBC can get an Adobe Fonts account to license it: https://fonts.adobe.com/fonts/adobe-caslon
